name: Docker-Compose

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
env :
    REGISTRY: ghcr.io/${{ github.actor }}
    DOCKER_REGISTRY-: ghcr.io/${{ github.actor }}
    DOCKER_REGISTRY: ghcr.io/${{ github.actor }}
jobs:
  Docker-compose_Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker-Compose Build
      run: docker-compose -f ./API-Minimizer/docker-compose.yml build


    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

    - name: Docker-Compose Push
      run: docker-compose -f ./API-Minimizer/docker-compose.yml push
    