# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  restore:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore API-Minimizer/API-Minimizer.sln

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build API-Minimizer/API-Minimizer.sln

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Tests
      run: dotnet test API-Minimizer/API-Minimizer.sln
      
    - name: Run Terraform CDK
      uses: hashicorp/terraform-cdk-action@v0.2
      with:
        cdktfVersion: 0.19.1
        terraformVersion: 1.5.2
        mode: plan-only
        stackName: my-stack
        terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
  
